name = "wwwuabot-api"
main = "src/index.ts"
compatibility_date = "2026-08-21"

# Default D1 binding (for local dev without --env)
[[d1_databases]]
binding = "DB"
database_name = "wwwuabot-db-dev"
database_id = "9fc03f61-d497-4d92-bae4-c92b02c2d1c5"

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "bda7a5fca58b4fbda87d75105d558ebf"

[env.dev]
name = "wwwuabot-api-dev"
[[env.dev.d1_databases]]
binding = "DB"
database_name = "wwwuabot-db-dev"
database_id = "9fc03f61-d497-4d92-bae4-c92b02c2d1c5"
[[env.dev.kv_namespaces]]
binding = "CONTENT_KV"
id = "bda7a5fca58b4fbda87d75105d558ebf"

[env.production]
name = "wwwuabot-api-prod"
[[env.production.d1_databases]]
binding = "DB"
database_name = "wwwuabot-db-prod"
database_id = "6e690692-7671-4598-826c-c2db591399a2"
[[env.production.kv_namespaces]]
binding = "CONTENT_KV"
id = "bda7a5fca58b4fbda87d75105d558ebf"
