name = "wwwuabot-web"
main = "src/worker.ts"
compatibility_date = "2026-08-21"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[env.dev]
name = "wwwuabot-web-dev"

[[env.dev.services]]
binding = "API"
service = "wwwuabot-api-dev"

[env.production]
name = "wwwuabot-web-prod"

[[env.production.services]]
binding = "API"
service = "wwwuabot-api-prod"
