name = "wwwuabot-web"
main = "src/worker.ts"
compatibility_date = "2026-08-21"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "single-page-application"

[env.dev]
name = "wwwuabot-web-dev"

[env.production]
name = "wwwuabot-web-prod"
